### PR TITLE
Bs 2 books search bar

### PR DESCRIPTION
**Pull request by code-bdani**
Book search is working & looks good.

### CODE REVIEW

**Comment by PhonethipLiu** [comment]
books search bar works. it's good to merge.

**Review by PhonethipLiu — COMMENTED** [review]
search bar items work. merge it!

**Comment by code-bdani** [comment]
Thanks, Phonethip.

**Review by PhonethipLiu — COMMENTED** [review]
search bar items work. merge it!

**Review by PhonethipLiu — APPROVED** [review]
page looks good

**Pull request merged**
